app:
  build: ./docker/httpd
  links:
    - db
  volumes_from:
    - appdata
  ports:
    - 19020:80

db:
  image: mariadb
  volumes_from:
    - dbdata
  ports:
    - 3306:3306
  environment:
    - MYSQL_ROOT_PASSWORD=fnord
    - MYSQL_DATABASE=fnord
    - MYSQL_USER=fnord
    - MYSQL_PASSWORD=fnord

appdata:
  image: tianon/true
  volumes:
    - ./:/var/www/html/

dbdata:
  image: tianon/true
  volumes:
    - ./data/mysql:/var/lib/mysql
