(form :action ,(action-url :add 'upload-images) :method "post" :enctype "multipart/form-data"
  (h1 "Upload")
  (a :class "cancel" :href ,(navi-url) ,(lang en "back"
                                              de "zurück"))
  (input :type "file" :name "image[]" :size "10")
  (input :type "file" :name "image[]" :size "10")
  (input :type "file" :name "image[]" :size "10")
  (input :type "file" :name "image[]" :size "10")
  (input :type "file" :name "image[]" :size "10")
  (input :type "file" :name "image[]" :size "10")
  (input :type "file" :name "image[]" :size "10")
  (input :type "file" :name "image[]" :size "10")
  (input :type "file" :name "image[]" :size "10")
  (input :type "file" :name "image[]" :size "10")
  (input :type "file" :name "image[]" :size "10")
  (input :type "file" :name "image[]" :size "10")
  (input :type "submit" :value "Upload…"))
